### PR TITLE
Create 11ty_404.md

### PR DESCRIPTION
**Pull request by cfjedimaster**
I gave this file a slightly "off" filename so to not accidentally conflict with a real 404 page (if that makes sense).

### CODE REVIEW

**Comment by peruvianidol** [comment]
Sorry, I didn't get a notification about this PR! This is great! Just a couple of things:

* Could you add your info in the front matter of this page? I want to make sure to credit people who contribute to the site. I haven't added any author data yet, but I'm thinking something like:
```
authorName: [Your name]
authorURL: [Your homepage or Twitter URL that will be linked from your name (Optional)]
```

* I started numbering the recipes because the date ordering wasn't consistent between local and production. Can you prefix your entry with "009-"?

Thanks!

**Comment by peruvianidol** [comment]
Now that I'm thinking about it, should we assume the user has already set up a template in **_includes**? If that's the case, you could just include `layout: base` in the front matter and include the body in the file:

```
This is where you should tell the user how to find their content. Maybe on the <a href="/">home page?</a>
```

**Comment by cfjedimaster** [comment]
Dumb question - will first off - this all makes sense. My GitFu is weak. If I go to the patch (https://github.com/cfjedimaster/11ty-recipes/blob/patch-1/recipes/11ty_404.md) and edit the file there, will that update the PR for you?

**Comment by peruvianidol** [comment]
Yeah, I think if you add any commits to the branch it should update the PR automatically.

**Comment by cfjedimaster** [comment]
I made 2 changes. I renamed the file. I added the front matter. I disagreed with the last comment because I'm not sure I understand what you mean by it. (Err, so I guess I don't disagree, I don't get it. ;) While I think nearly all 11ty files will use a layout of some sort, and having it in maybe makes it more realistic, but it's also not really necessary as we just want the user to do _some_ kinda file. The actual contents don't matter.

That being said, I wasn't sure if you were suggesting just adding the front matter, or adding the file too. If so, I think it's too much then and we should keep to one file.

**Comment by peruvianidol** [comment]
My thinking was if the user has already done [this recipe](https://11ty.recipes/recipes/add-a-layout/), we could add is as a prerequisite (as in [this recipe](https://11ty.recipes/recipes/create-a-github-repository-for-your-eleventy-site/)). Then the 404 page in the example would look like this rather than including all the HTML, and the title would get passed into the template so you wouldn't need the header either.

```
---
title: Oops! Not found
layout: base
permalink: /404.html
---

This is where you should tell the user how to find their content. Maybe on the <a href="/">home page?</a>
```

**Comment by peruvianidol** [comment]
Not that you'd need to worry about this if you make the above change, but for future reference, in order to escape Nunjucks inside of a code block you can use `{% raw %}`:

```
{% raw %}{{ title }}{% endraw %}
```

Right now it's using the title from your recipe. :)

**Comment by cfjedimaster** [comment]
I'd be worried about people doing the recipes in order. In fact, specifically for this type of content, I'd expect most users to not go in order.

That being said, if you want the change, I don't feel super strongly about it. :) Let me know and I'll do so!

**Comment by peruvianidol** [comment]
Not that the user necessarily has to do them in order, but I think it's helpful to build on other recipes rather than having to repeat a lot of things. If they already have layouts set up, which is pretty useful in other contexts, making a 404 page is that much easier. That said, it's pretty early and I'm still figuring out what 11ty.recipes is.

**Comment by cfjedimaster** [comment]
Good enough for me! I also changed he link to Markdown. Let me know if good!

**Comment by peruvianidol** [comment]
Awesome. Thanks, Raymond!

**Pull request merged**
